### ISSUE TITLE
Incorrect terminology

### ISSUE THREAD

**Issue by sampablokuper** [pre-commit/pre-commit.github.io#70]
In your [documentation](https://github.com/pre-commit/pre-commit.github.io/blob/real_master/index.mako) and perhaps also in your code, you use "sha" when you appear to mean "hash", or more likely "commit".

Using the wrong word causes potential for confusion, and is also - in this case - a hostage to fortune, because there is no guarantee that future (versions of) version control repositories will use hashes from the [Secure Hash Algorithm ("SHA")](https://en.wikipedia.org/wiki/Secure_Hash_Algorithm) family of hashing algorithms to refer to commits.

This may be a minor bug, but it is still a bug.

It would be great if you could refactor your code and documentation to fix it in the next patch release, and stop supporting the incorrect term (e.g. where it appears in `.pre-commit-config.yaml`) in the next major release.

**Comment by asottile** [comment]
sha is technically correct for git (which uses [SHA-1](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects) to represent internal objects),  however I plan to change that key anyway.

It's unfortunately a difficult breaking change that I've planned to do for quite some time but haven't gotten around to implementing it.

https://github.com/pre-commit/pre-commit/issues/106 tracks this work.  I plan to replace the key with `ref` since the value can also be a tag.

**Comment by sampablokuper** [comment]
> sha is technically correct for git (which uses SHA-1 to represent internal objects),

No, it is not technically correct for Git. Git uses SHA-1 *hashes* to represent internal objects.

> however I plan to change that key anyway.

Cool :)

> It's unfortunately a difficult breaking change that I've planned to do for quite some time but haven't gotten around to implementing it.

Fair enough!

> pre-commit/pre-commit#106 tracks this work. I plan to replace the key with ref since the value can also be a tag.

That sounds reasonable. Thanks.
